# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_documenttype_is_moderated_and_more'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='documents',
            field=models.ManyToManyField(related_name='dislikes', to='document.document'),
        ),
        migrations.AlterField(
            model_name='like',
            name='documents',
            field=models.ManyToManyField(related_name='likes', to='document.document'),
        ),
    ]
