# Generated by Django 4.1.5 on 2023-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_alter_dislike_documents_alter_like_documents'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dislike',
            table='cmnDislike',
        ),
        migrations.AlterModelTable(
            name='like',
            table='cmnLike',
        ),
    ]
