# Generated by Django 4.1.5 on 2023-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_document_update_by_documenttype_is_active_type_and_more'),
        ('reactions', '0003_alter_dislike_table_alter_like_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='documents',
            field=models.ManyToManyField(db_table='docDocumentDislikes', related_name='dislikes', to='document.document'),
        ),
        migrations.AlterField(
            model_name='like',
            name='documents',
            field=models.ManyToManyField(db_table='docDocumentLikes', related_name='likes', to='document.document'),
        ),
    ]
