# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_create_at_alter_document_create_by_and_more'),
        ('reactions', '0004_alter_dislike_documents_alter_like_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='documents',
            field=models.ManyToManyField(db_table='doc_document_dislikes', related_name='dislikes', to='document.document'),
        ),
        migrations.AlterField(
            model_name='like',
            name='documents',
            field=models.ManyToManyField(db_table='doc_document_likes', related_name='likes', to='document.document'),
        ),
        migrations.AlterModelTable(
            name='dislike',
            table='cmn_dislike',
        ),
        migrations.AlterModelTable(
            name='like',
            table='cmn_like',
        ),
    ]
