# Generated by Django 4.1.5 on 2023-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(null=True)),
                ('is_ready_for_publish', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'doc_document',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('doc_type', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('is_accept_for_comments', models.BooleanField(default=True)),
                ('is_accept_for_reactions', models.BooleanField(default=True)),
                ('is_accept_for_tags', models.BooleanField(default=True)),
                ('is_admin_level_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'doc_document_type',
            },
        ),
    ]
