# Generated by Django 4.1.5 on 2023-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
    ]
