# Generated by Django 4.1.5 on 2023-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documenttype_is_moderated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='is_moderated',
        ),
        migrations.AddField(
            model_name='document',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
    ]
