# Generated by Django 4.1.5 on 2023-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_documenttype_is_moderated_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='docDocument',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='docDocumentType',
        ),
    ]
