# Generated by Django 4.1.5 on 2023-02-21 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_alter_document_table_alter_documenttype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='update_by',
            field=models.ForeignKey(db_column='updateBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active_type',
            field=models.BooleanField(db_column='isActiveType', default=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_need_approve',
            field=models.BooleanField(db_column='isNeedApprove', default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createAt'),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_by',
            field=models.ForeignKey(db_column='createBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(db_column='docType', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_moderated',
            field=models.BooleanField(db_column='isModerated', default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_ready_for_publish',
            field=models.BooleanField(db_column='isReadyForPublish', default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='json_data',
            field=models.JSONField(db_column='dataJSON', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_at',
            field=models.DateTimeField(db_column='updateAt', null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='doc_type',
            field=models.CharField(db_column='docType', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_comments',
            field=models.BooleanField(db_column='isAcceptForCommentaries', default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_reactions',
            field=models.BooleanField(db_column='isAcceptForReactions', default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_tags',
            field=models.BooleanField(db_column='isAcceptForTags', default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_admin_level_only',
            field=models.BooleanField(db_column='isAdminLevelOnly', default=False),
        ),
    ]
