# Generated by Django 4.1.5 on 2023-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_document_update_by_documenttype_is_active_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_id',
            field=models.CharField(blank=True, db_column='typeId', max_length=90, null=True, unique=True),
        ),
    ]
