# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0007_document_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_ready_for_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='json_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_id',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='doc_type',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_accept_for_tags',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_admin_level_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_need_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='document',
            table='doc_document',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='doc_document_type',
        ),
    ]
