# Generated by Django 4.1.7 on 2023-03-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0008_alter_document_create_at_alter_document_create_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='document.document')),
            ],
            options={
                'db_table': 'fc_department',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='document.document')),
            ],
            options={
                'db_table': 'fc_direction',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('direction', models.ManyToManyField(db_table='fc_lecturer_direction', to='structure.direction')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='document.document')),
            ],
            options={
                'db_table': 'fc_lecturer',
            },
        ),
    ]
