# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0004_remove_documenttype_is_moderated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('file_type', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'fl_file_type',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fl_user_file',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filetype')),
            ],
            options={
                'db_table': 'fl_file',
                'ordering': ['id'],
            },
        ),
    ]
