# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_table_alter_filetype_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='fs_document_file',
        ),
        migrations.AlterModelTable(
            name='filetype',
            table='fs_file_type',
        ),
        migrations.AlterModelTable(
            name='userfile',
            table='fs_person_file',
        ),
    ]
