# Generated by Django 4.1.7 on 2023-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_create_at_alter_document_create_by_and_more'),
        ('files', '0004_filetype_save_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='document.document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=4000),
        ),
    ]
