# Generated by Django 4.1.7 on 2023-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_doc_alter_file_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='fs_file',
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
