# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questionandanswers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionandanswers',
            table='qna_question',
        ),
        migrations.AlterModelTable(
            name='questiontype',
            table='qna_question_type',
        ),
    ]
