# Generated by Django 4.1.5 on 2023-01-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_code_email_dt_alter_user_code_password_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('int_level', models.IntegerField()),
            ],
            options={
                'db_table': 'usr_role',
                'ordering': ['int_level'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role'),
        ),
    ]
