# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_email_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_password_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
    ]
