# Generated by Django 4.1.5 on 2023-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_code_email_dt_alter_user_code_password_dt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='prsPerson',
        ),
    ]
