# Generated by Django 4.1.5 on 2023-02-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='prsRole',
        ),
    ]
