# Generated by Django 4.1.5 on 2023-02-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesstokens',
            table='prsPersonAccessToken',
        ),
        migrations.AlterModelTable(
            name='refreshtokens',
            table='prsPersonRefreshToken',
        ),
        migrations.AlterModelTable(
            name='user',
            table='prsPerson',
        ),
    ]
