# Generated by Django 4.1.5 on 2023-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_accesstokens_table_alter_refreshtokens_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstokens',
            name='valid_to',
            field=models.DateTimeField(db_column='validTo', default=None),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='valid_to',
            field=models.DateTimeField(db_column='validTo', default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_email',
            field=models.TextField(blank=True, db_column='codeRegister', default=None, null=True, verbose_name='Токен для подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_email_dt',
            field=models.DateTimeField(blank=True, db_column='codeRegisterEndDt', null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_password',
            field=models.CharField(blank=True, db_column='codePasswordChange', default=None, max_length=1024, null=True, verbose_name='Токен для замены пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_password_dt',
            field=models.DateTimeField(blank=True, db_column='codePasswordChangeEndDt', null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed_email',
            field=models.BooleanField(db_column='isConfirmedEmail', default=False, verbose_name='Почта подтверждена?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_graduate',
            field=models.BooleanField(db_column='isGraduate', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(db_column='isLecturer', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_stand',
            field=models.BooleanField(db_column='isStand', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, db_column='middleName', default=None, max_length=32, null=True, verbose_name='Отчество'),
        ),
    ]
