# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_accesstokens_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstokens',
            name='valid_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='valid_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_email',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Токен для подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_email_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_password',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Токен для замены пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_password_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed_email',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterModelTable(
            name='accesstokens',
            table='prs_access_token',
        ),
        migrations.AlterModelTable(
            name='refreshtokens',
            table='prs_refresh_token',
        ),
        migrations.AlterModelTable(
            name='role',
            table='prs_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='prs_person',
        ),
    ]
