# Generated by Django 4.1.5 on 2023-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('documents', models.ManyToManyField(related_name='tags', to='document.document')),
            ],
            options={
                'db_table': 'cmn_tag',
            },
        ),
    ]
