# Generated by Django 4.1.5 on 2023-02-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_table_alter_documenttype_table'),
        ('tags', '0002_alter_tag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='documents',
            field=models.ManyToManyField(db_table='docDocumentTag', related_name='tags', to='document.document'),
        ),
    ]
