# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_create_at_alter_document_create_by_and_more'),
        ('tags', '0003_alter_tag_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='documents',
            field=models.ManyToManyField(db_table='doc_document_tag', related_name='tags', to='document.document'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='cmn_tag',
        ),
    ]
