# Generated by Django 4.1.5 on 2023-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='childcommentary',
            table='cmnCommentaryChild',
        ),
        migrations.AlterModelTable(
            name='commentary',
            table='cmnCommentary',
        ),
    ]
