# Generated by Django 4.1.5 on 2023-02-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentaries', '0003_alter_childcommentary_table_alter_commentary_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcommentary',
            name='create_by',
            field=models.ForeignKey(db_column='createBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childcommentary',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, db_column='createDt'),
        ),
        migrations.AlterField(
            model_name='childcommentary',
            name='update_dt',
            field=models.DateTimeField(db_column='updateDt', null=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='create_by',
            field=models.ForeignKey(db_column='createBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, db_column='createDt'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='update_dt',
            field=models.DateTimeField(db_column='updateDt', null=True),
        ),
    ]
