# Generated by Django 4.1.7 on 2023-03-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentaries', '0004_alter_childcommentary_create_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcommentary',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childcommentary',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='childcommentary',
            name='update_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='update_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='childcommentary',
            table='cmn_commentary_child',
        ),
        migrations.AlterModelTable(
            name='commentary',
            table='cmn_commentary',
        ),
    ]
